---
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - prettier
  - "plugin:react/recommended"
plugins:
  - "@typescript-eslint"
  - prettier
  - react
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: latest
overrides: []
env:
  browser: true
  es2021: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prettier/prettier:
    - error
ignorePatterns:
  - "*.*.js"